export const LOGOUT = "LOGOUT"
export const VALIDATE_OTP_RESPONSE = "VALIDATE_OTP_RESPONSE"
export const EMAIL_SEND = "EMAIL_SEND"
export const PHONE_NUMBER ="PHONE_NUMBER"
export const EMAIL_SET = "EMAIL_SET"
export const SET_NAME = "SET_NAME"
export const SET_DOB = "SET_DOB"
export const SET_LANG = "SET_LANG"
export const SET_COUNTRIES = "SET_COUNTRIES"
export const SET_CITY = "SET_CITY"
export const CITY_ERROR = "CITY_ERROR"
export const USERDATA = "USERDATA"
export const  MEMBERSHIP = "MEMBERSHIP"
export const  ADD_LIST = "ADD_LIST"
export const  GET_LIST = "GET_LIST"
export const  GET_PROFILE = "GET_PROFILE"

