import React, { useEffect, useState } from "react";
import Head from "next/head";
import { getSession, useSession } from "next-auth/react";
import Login from "@/components/Login";
import Navbar from "@/components/Navbar";
import requests from "@/utils/requests";
import Hero from "@/components/Hero";
import Row from "@/components/Row";
import Link from 'next/link';
import { useRouter } from "next/router";
import { useDispatch, useSelector } from 'react-redux'




export default function Home(){
  const router = useRouter();
  const { data: session } = useSession();
  const dispatch = useDispatch();

  if (session) {
    // If user is not logged in, redirect to the login page
    router.push("/login"); // Replace "/login" with your login page URL
    return <Login/>;
  }

  const profile_data = useSelector((state) => state.auth.profile_data)
  console.log("profile_data---",profile_data)

  

  return (
    <>
      <Head>
        <title>Webntertenmaint</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="relative bg-gradient-to-b from-gray-900/10 to-[#010511]">
        <Navbar />
        <div className="flex justify-center items-center mt-14 mb-7">
          <p className="uppercase text-2xl">Choose your entertainment</p>
        </div>
        <div className="flex justify-center items-center">

          <div className="grid grid-cols-2 gap-4">
            <Link href="/StoryTeller">
              <div className="storyteller p-4">
              </div>
            </Link>

            <Link href="/Musicon">
              <div className="musicon p-4">
              </div>
            </Link>

            <Link href="/LifeStyle">
              <div className="lifestyle p-4">
              </div>
            </Link>

            <Link href="/SoundTrack">
              <div className="soundtrack p-4">
              </div>
            </Link>
          </div>
        </div>
       
      </main>
    </>
  );
}

export async function getServerSideProps(context) {
  const session = await getSession(context);

  // If there's no session, redirect to login page
  if (session) {
    return {
      redirect: {
        destination: '/', // Replace "/login" with your login page URL
        permanent: false,
      },
    };
  }

  // If there's a session, allow rendering the Home page
  return {
    props: {}, // You can pass props if needed
  };
}

